config/routes.rb
Rails.application.routes.draw do
  resources :distros do
    resources :repos, shallow: true
    resources :debian_repos, controller: "repos", type: "DebianRepo", shallow: true, path: "repos"
    resources :debian_source_repos, controller: "repos", type: "DebianSourceRepo", shallow: true, path: "repos"
  end

  get "repos/:id/fetch", to: "repos#fetch", as: :fetch_repo
  get "repos/:id/fetch_status", to: "repos#fetch_status", as: :fetch_status_repo
  get "repos/:id/view_fetch", to: "repos#view_fetch", as: :view_fetch_repo
  get "repos/:id/packages/:page_num", to: "repos#show", as: :packages_repo
  get "repos/:id/packages/:page_num/edit", to: "repos#edit_packages", as: :edit_packages_repo
  patch "repos/:id/packages/:page_num", to: "repos#update_packages"
  put "repos/:id/packages/:page_num", to: "repos#update_packages"

  resources :software
  get "search_redirect", to: "software#search_redirect", as: :software_search_form
  get "search/:query", to: "software#search", as: :software_search

  root 'software#landing'

end

app/models/repo.rb
class Repo < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :type, presence: true
	validates :url, presence: true, uniqueness: true
	validates :distro, presence: true
	belongs_to :distro
	has_many :packages, dependent: :destroy
	serialize :fetch_info, Hash

	# fetch metadata cols:
	# => last_fetch, DateTime, date when fetch method was last run
	# => fetch_last_version, Float, version of release file from last fetch
	# => fetch_last_date, DateTime, date of release file from last fetch
	# => is_fetching, Boolean, is the fetch method currently running
	# => fetch_log, String, log from the last fetch

	def self.types
		[
			"DebianRepo",
			"DebianSourceRepo"
		]
	end

	def clear_fetch_log
		self.fetch_log = ""
		self.save
	end

	def log_fetch(msg)
		self.fetch_log << msg
		print msg
		self.save
	end

	def fetch
		raise 'Abstract method'
	end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
	before_action :get_repo, only: [:show, :edit_packages, :update_packages, :edit, :update, :destroy, :fetch, :fetch_status, :view_fetch]
	before_action :get_repo_types, only: [:new, :edit_packages, :edit, :fetch, :view_fetch]
	before_action :get_distro, only: [:new, :create]
	before_action :get_repo_distro, only: [:show, :edit_packages, :edit, :destroy, :fetch, :view_fetch]
	before_action :get_repo_type_name, only: [:show, :fetch, :view_fetch]

	def get_repo
		@repo = Repo.find(params[:id])
	end

	def get_repo_types
		@repo_types = Repo.types
	end

	def get_distro
		@distro = Distro.find(params[:distro_id])
	end

	def get_repo_distro
		@distro = @repo.distro
	end

	def get_repo_type_name
		@repo_type_name = @repo.type.constantize.type_name
	end

	def show
		@page_num = (params.has_key?(:page_num)) ? params[:page_num].to_i : 1
		@per_page = 50
		@num_pages = (@repo.packages.length / @per_page.to_f).ceil

		if @repo.packages.length > 0 && @page_num > @num_pages
			redirect_to @repo
		end

		if @num_pages % 10 != 0 && @page_num > (@num_pages / 10.0).floor * 10
			@page_range = ((@num_pages / 10.0).floor * 10 + 1)..@num_pages
		elsif @page_num % 10 == 0
			@page_range = (@page_num - 9)..@page_num
		else
			@page_range = ((@page_num / 10.0).floor * 10 + 1)..((@page_num / 10.0).ceil * 10)
		end

		@packages = @repo.packages[(@per_page * (@page_num - 1))..(@per_page * (@page_num - 1) + @per_page - 1)]
	end

	def edit_packages
		if @repo.packages.length == 0
			redirect_to @repo
		end

		@page_num = (params.has_key?(:page_num)) ? params[:page_num].to_i : 1
		@per_page = 50
		@num_pages = (@repo.packages.length / @per_page.to_f).ceil

		if @repo.packages.length > 0 && @page_num > @num_pages
			redirect_to @repo
		end

		if @num_pages % 10 != 0 && @page_num > (@num_pages / 10.0).floor * 10
			@page_range = ((@num_pages / 10.0).floor * 10 + 1)..@num_pages
		elsif @page_num % 10 == 0
			@page_range = (@page_num - 9)..@page_num
		else
			@page_range = ((@page_num / 10.0).floor * 10 + 1)..((@page_num / 10.0).ceil * 10)
		end

		@packages = @repo.packages[(@per_page * (@page_num - 1))..(@per_page * (@page_num - 1) + @per_page - 1)]
	end

	def update_packages
		@page_num = (params.has_key?(:page_num)) ? params[:page_num].to_i : 1

		params.require(:package).each do |id, software|
			Package.find(id).update({software: Software.find_by(name: software)})
		end

		redirect_to packages_repo_path(@repo, @page_num)
	end

	def new
		@repo = Repo.new
	end

	def create
		@repo = Repo.new(params.require(:repo).permit([:name, :type, :url]))
		@repo.distro = Distro.find(params[:distro_id])
		@repo.save
		redirect_to repo_path(@repo)
	end

	def edit
	end

	def update
		if @repo.update(params.require(@repo.type.underscore.to_sym).permit([:name, :type, :url]))
			redirect_to @repo
		else
			render action: "edit"
		end
	end

	def destroy
		@repo.destroy
		redirect_to @distro
	end

	def fetch
		if !@repo.is_fetching && !@repo.is_fetch_queued
			@repo.is_fetch_queued = true
			@repo.save
			FetchPackageListJob.perform_later(@repo.id)
		end
	end

	def fetch_status
		render json: {is_fetching: @repo.is_fetching, is_fetch_queued: @repo.is_fetch_queued, fetch_log: @repo.fetch_log}
	end

	def view_fetch
		if @repo.is_fetching || @repo.is_fetch_queued
			redirect_to fetch_repo_path(@repo)
		end

		if @repo.last_fetch == nil || @repo.fetch_info.empty?
			redirect_to @repo
		end

		@removed = Array.new
		@repo.fetch_info[:removed].each do |package_id|
			@removed << Package.find(package_id)
		end
	end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_for @repo, url: url, method: method do |f| %>
<div class="form-group">
	<%= f.label :name %>
	<%=	f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :type, "Repo Type" %>
	<%=	f.select :type, @repo_types.collect {|repo_type| [repo_type.constantize.type_name, repo_type]}, {}, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :url, "URL" %>
	<%=	f.text_field :url, class: "form-control" %>
</div>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/repos/_heading.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<div class="pull-left">
				<h1>
					<%= link_to @distro.name, @distro %> &gt; <% if !current_page?(repo_path(@repo)) %><%= link_to @repo.name, @repo %><% else %><%= @repo.name %><% end %><br />
					<small><span class="label label-default"><%= @repo_type_name %></span> <%= @repo.url %></small>
				</h1>
			</div>
			<div class="pull-right">
				<% if !current_page?(fetch_repo_path(@repo)) %>
				<% if @repo.is_fetching %>
				<%= link_to "Fetching Packages...", fetch_repo_path(@repo), class: "btn btn-success" %>
				<% elsif @repo.is_fetch_queued %>
				<%= link_to "Fetch Queued", fetch_repo_path(@repo), class: "btn btn-info" %>
				<% elsif !@repo.fetch_info.empty? %>
				<div class="btn-group">
					<%= link_to "View Last Fetch", view_fetch_repo_path(@repo), class: "btn btn-primary" %>
					<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="caret"></span>
						<span class="sr-only">Toggle Dropdown</span>
					</button>
					<ul class="dropdown-menu">
						<li><%= link_to "Fetch Packages", fetch_repo_path(@repo) %></li>
					</ul>
				</div>
				<% else %>
				<%= link_to "Fetch Packages", fetch_repo_path(@repo), class: "btn btn-primary" %>
				<% end %>
				<% end %>
				&nbsp;<%= link_to "Edit", edit_repo_path(@repo), class: "btn btn-default" %>&nbsp;&nbsp;<%= link_to "Delete", @repo, :method => :delete, class: "btn btn-danger" %>
				<br />
			</div>
		</div>
	</div>
</div>

app/views/repos/edit.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1><%= link_to @distro.name, @distro %> &gt; Edit <%= @repo.name %></h1>
		</div>
		<%= render partial: 'form', locals: {url: @repo, method: :patch} %>
	</div>
</div>

app/views/repos/edit_packages.html.erb
<%= render "heading" %>
<div class="row">
	<div class="col-xs-12">
		<h2>Assign Packages</h2>
		<%= form_for :packages, url: packages_repo_path(@repo, @page_num), method: :patch do |f| %>
			<div class="form-group">
				<table class="table table-inline">
					<% @packages.each do |package| %>
					<tr><td><h4><%= package.name %> <nobr><small><%= package.version %></small></nobr></h4></td><td><h4>&rarr;</h4></td><td><%= text_field :package, package.id, value: (package.software) ? package.software.name : "", size: 100, autocomplete: "off", class: "form-control typeahead-softwares" %></td></tr>
					<% end %>
				</table>
			</div>
			<%= f.submit "Assign", class: "btn btn-primary" %>&nbsp;&nbsp;<%= link_to "Cancel", @repo, class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/repos/fetch.html.erb
<%= render "heading" %>
<div class="row">
	<div class="col-xs-12">
		<h2 id="title">
			<% if @repo.is_fetching %>
			Fetching packages....
			<% elsif @repo.is_fetch_queued %>
			Waiting for fetch to start...
			<% else %>
			Fetch completed.
			<% end %>
		</h2>
		<pre data-fetch-status="<%= fetch_status_repo_path(@repo) %>"><% if @repo.is_fetching || (!@repo.is_fetching && !@repo.is_fetch_queued) %><%= @repo.fetch_log %><% elsif @repo.is_fetch_queued %>Fetch has been queued.<% end %></pre>
		<br />
		<%= link_to "Back", @repo, class: "btn btn-primary" %>
	</div>
</div>

app/views/repos/new.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1><%= link_to @distro.name, @distro %> &gt; Add Repo</h1>
		</div>
		<%= render partial: 'form', locals: {url: distro_repos_path, method: :post} %>
	</div>
</div>

app/views/repos/show.html.erb
<%= render "heading" %>
<div class="row">
	<div class="col-xs-6"><h2>Packages (<%= @repo.packages.length %>)</h2></div>
	<div class="col-xs-6"><div class="pull-right"><% if @repo.packages.length != 0 %><%= link_to "Assign Software", edit_packages_repo_path(@repo, @page_num), class: "btn btn-primary" %><% end %></div></div>
</div>
<div class="row">
	<div class="col-xs-12">
		<% if @repo.packages.length == 0 %>
		<span>There are no packages in this repo.</span>
		<% else %>
		<table class="table table-inline">
			<% @packages.each do |package| %>
			<tr><td><h4><%= package.name %> <nobr><small><%= package.version %></small></nobr></h4></td><td><% if package.software %><h4>&rarr;</h4><% end %></td><td><% if package.software %><h4><%= link_to package.software.name, package.software %></h4><% end %></td></tr>
			<% end %>
		</table>
		<nav>
			<ul class="pagination">
				<li<% if @page_num == 1 %> class="disabled"<% end %>><a href="<%= packages_repo_path @repo, @page_num - 1 %>" aria-label="Previous"><span aria-hiddin="true">&laquo;</span></a></li>
				<% for i in @page_range do %>
				<li<% if i == @page_num %> class="active"<% end %>><a href="<%= packages_repo_path @repo, i %>"><%= i %></a></li>
				<% end %>
				<li<% if @page_num == @num_pages %> class="disabled"<% end %>><a href="<%= packages_repo_path @repo, @page_num + 1 %>" aria-label="Next"><span aria-hiddin="true">&raquo;</span></a></li>
			</ul>
		</nav>
		<% end %>
	</div>
</div>

app/views/repos/view_fetch.html.erb
<%= render "heading" %>
<div class="row">
	<div class="col-xs-12">
		<h2>Fetch @ <%= @repo.last_fetch.strftime("%-m/%-d/%y %-I:%-M:%-S %p %Z") %></h2>
		<table class="table table-hover">
			<tr><th colspan="2"><h3>Release Info</h3></th></tr>
			<tr><th>Version:</th><td><%= @repo.fetch_last_version %></td></tr>
			<tr><th>Date:</th><td><%= @repo.fetch_last_date %></td></tr>
			<tr><th colspan="2"><h3>Package Info</h3></th></tr>
			<tr><th>New:</th><td><%= @repo.fetch_info[:new] %></td></tr>
			<tr><th>Updated:</th><td><%= @repo.fetch_info[:updated] %></td></tr>
			<tr><th>Not Updated:</th><td><%= @repo.fetch_info[:not_updated] %></td></tr>
			<tr><th>Removed:</th><td><%= @repo.fetch_info[:removed].length %></td></tr>
			<tr><th>Conflicts:</th><td><%= @repo.fetch_info[:updated_conflicts].length %></td></tr>
		</table>
		<% if @repo.fetch_info[:updated_conflicts].length > 0 %>
		<h3>Update Conflicts</h3>
		<% @repo.fetch_info[:updated_conflicts].each do |conflict| %>
		<% conflict.each |package| %>
		<h4><%= package[:name] %> <small><%= package[:version] %></small></h4>
		<% end %>
		<% end %>
		<% if @removed.length > 0 %>
		<h3>Removed Packages</h3>
		<% @removed.each do |package| %>
		<h4><%= package.name %> <small><%= package.version %></small></h4>
		<% end %>
		<% end %>
		<h3>Fetch Log</h3>
		<pre><%= @repo.fetch_log %></pre>
	</div>
</div>