config/routes.rb
Rails.application.routes.draw do
  resources :distros do
    resources :repos, shallow: true
    resources :debian_repos, controller: "repos", type: "DebianRepo", shallow: true, path: "repos"
    resources :debian_source_repos, controller: "repos", type: "DebianSourceRepo", shallow: true, path: "repos"
  end

  get "repos/:id/fetch", to: "repos#fetch", as: :fetch_repo
  get "repos/:id/fetch_status", to: "repos#fetch_status", as: :fetch_status_repo
  get "repos/:id/view_fetch", to: "repos#view_fetch", as: :view_fetch_repo
  get "repos/:id/packages/:page_num", to: "repos#show", as: :packages_repo
  get "repos/:id/packages/:page_num/edit", to: "repos#edit_packages", as: :edit_packages_repo
  patch "repos/:id/packages/:page_num", to: "repos#update_packages"
  put "repos/:id/packages/:page_num", to: "repos#update_packages"

  resources :software
  get "search_redirect", to: "software#search_redirect", as: :software_search_form
  get "search/:query", to: "software#search", as: :software_search

  root 'software#landing'

end

app/models/distro.rb
class Distro < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	has_many :repos, dependent: :destroy
end

app/controllers/distros_controller.rb
class DistrosController < ApplicationController
  before_action :get_distro, only: [:show, :edit, :update, :destroy]

  def get_distro
  	@distro = Distro.find(params[:id])
  end

  def new
    @distro = Distro.new
  end

  def create
  	@distro = Distro.create(params.require(:distro).permit(:name))
  	redirect_to @distro
  end

  def index
  	@distros = Distro.all
  end

  def show
  end

  def edit
  end

  def update
  	@distro.update(params.require(:distro).permit(:name))
    redirect_to action: "show"
  end

  def destroy
    @distro.destroy
    redirect_to action: "index"
  end
end

app/helpers/distros_helper.rb
module DistrosHelper
end

app/views/distros/_form.html.erb
<%= form_for @distro, url: url, method: method do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%=	f.text_field :name, class: "form-control" %>
	</div>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/distros/edit.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1>Edit <%= @distro.name %></h1>
		</div>
		<%= render partial: 'form', locals: {url: @distro, method: :patch} %>
	</div>
</div>

app/views/distros/index.html.erb
<div class="row">
	<div class="page-header">
		<div class="col-xs-8"><h1>Linux Distros</h1></div>
		<div class="col-xs-4 text-right"><%= link_to "Add", new_distro_path, class: "btn btn-primary" %></div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<% if @distros.length == 0 %>
		<span>No distros found.</span>
		<% end %>
		<% @distros.each do |distro| %>
		<h2><%= link_to distro.name, distro %></h2>
		<% end %>
	</div>
</div>

app/views/distros/new.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1>Add Linux Distro</h1>
		</div>
		<%= render partial: 'form', locals: {url: distros_path, method: :post} %>
	</div>
</div>

app/views/distros/show.html.erb
<div class="row">
	<div class="page-header">
		<div class="col-xs-6"><h1><%= @distro.name %></h1></div>
		<div class="col-xs-6 text-right"><%= link_to "Edit", edit_distro_path(@distro), class: "btn btn-default" %>&nbsp;&nbsp;<%= link_to "Delete", @distro, :method => :delete, class: "btn btn-danger" %></div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<h2>Repos</h2>
		<% @distro.repos.each do |repo| %>
		<h3>
			<%= link_to repo.name, repo_path(repo) %>&nbsp;&nbsp;
			<small><%= pluralize repo.packages.length, "Package" %></small>
			<% if !repo.fetch_info.empty? && (repo.fetch_info[:updated_conflicts].length > 0 || repo.fetch_info[:removed].length > 0) %>
			&nbsp;&nbsp;<small><span class="label label-danger label-large-nomargin">action required</span></small>
			<% elsif repo.is_fetching %>
			&nbsp;&nbsp;<small><span class="label label-success label-large-nomargin">fetching</span></small>
			<% elsif repo.is_fetch_queued %>
			&nbsp;&nbsp;<small><span class="label label-info label-large-nomargin">queued</span></small>
			<% end %>
		</h3>
		<% end %>
		<br />
		<%= link_to "Add Repo", new_distro_repo_path(@distro), class: "btn btn-primary" %>
	</div>
</div>