config/routes.rb
Rails.application.routes.draw do
  resources :distros do
    resources :repos, shallow: true
    resources :debian_repos, controller: "repos", type: "DebianRepo", shallow: true, path: "repos"
    resources :debian_source_repos, controller: "repos", type: "DebianSourceRepo", shallow: true, path: "repos"
  end

  get "repos/:id/fetch", to: "repos#fetch", as: :fetch_repo
  get "repos/:id/fetch_status", to: "repos#fetch_status", as: :fetch_status_repo
  get "repos/:id/view_fetch", to: "repos#view_fetch", as: :view_fetch_repo
  get "repos/:id/packages/:page_num", to: "repos#show", as: :packages_repo
  get "repos/:id/packages/:page_num/edit", to: "repos#edit_packages", as: :edit_packages_repo
  patch "repos/:id/packages/:page_num", to: "repos#update_packages"
  put "repos/:id/packages/:page_num", to: "repos#update_packages"

  resources :software
  get "search_redirect", to: "software#search_redirect", as: :software_search_form
  get "search/:query", to: "software#search", as: :software_search

  root 'software#landing'

end

app/models/software.rb
class Software < ActiveRecord::Base
	has_many :packages
	validates :name, presence: true, uniqueness: true
	searchkick text_start: [:name]
end

app/controllers/software_controller.rb
class SoftwareController < ApplicationController
	before_action :get_software_index, only: [:index]
	before_action :get_software, only: [:edit, :update, :show, :destroy]

	def get_software_index
		@software_index = Software.all
	end

	def get_software
		@software = Software.find(params[:id])
	end

	def software_params
		params.require(:software).permit(:name, :short_description, :description, :url, :license)
	end

	def landing
		@recent_softwares = Software.all.order(updated_at: :desc).limit(5)
		@num_softwares = Software.all.length
		@num_packages = Package.all.length
		@num_distros = Distro.all.length
		@num_repos = Repo.all.length
	end
	
	def index
		respond_to do |format|
			format.html
			format.json { render json: Software.all.collect {|s| {name: s.name, description: s.short_description, url: s.url, license: s.license, tags: s.tags}} }
		end
	end

	def new
		@software = Software.new
	end

	def create
		@software = Software.new(software_params)
		if @software.save
			redirect_to @software
		else
			render action: 'new'
		end
	end

	def edit
	end

	def update
		if @software.update(software_params)
			redirect_to @software
		else
			render action: 'edit'
		end
	end

	def show
		@packages = Array.new

		Distro.all.each do |d|
			d_hash = Hash.new
			d_hash[:distro] = d.name
			d_hash[:packages] = Array.new
			d.repos.each do |r|
				r.packages.where(software: @software).each do |s|
					d_hash[:packages] << {name: s.name, version: s.version, description: s.description}
				end
			end
			@packages << d_hash
		end
	end

	def destroy
	end

	def search_redirect
		if !params.has_key?(:query)
			redirect_to action: "index"
		end

		redirect_to software_search_path(params[:query])
	end

	def search
		if !params.has_key?(:query)
			redirect_to action: "index"
		end

		respond_to do |format|
			format.html {
				@search_query = params[:query].to_s
				@search_results = Software.search(params[:query], fields: [{name: :word}])
			}
			format.json { render json: Software.search(params[:query], fields: [{name: :text_start}], limit: 10).map(&:name) }
		end
	end
end

app/helpers/software_helper.rb
module SoftwareHelper
end

app/views/software/_form.html.erb
<%= form_for @software, url: url, method: method do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%=	f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :short_description, "Short Description" %>
		<%=	f.text_field :short_description, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%=	f.text_area :description, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :url, "URL" %>
		<%=	f.text_field :url, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :license %>
		<%=	f.text_field :license, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :tags %>
		<%=	f.text_field :tags, class: "form-control" %>
	</div>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/software/edit.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1>Edit <%= @software.name %></h1>
		</div>
		<%= render partial: 'form', locals: {url: @software, method: :patch} %>
	</div>
</div>

app/views/software/index.html.erb
<div class="row">
	<div class="page-header">
		<div class="col-xs-8"><h1>Software</h1></div>
		<div class="col-xs-4 text-right"><%= link_to "Add", new_software_path, class: "btn btn-primary" %></div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<% if @software_index.length == 0 %>
		<span>No software found.</span>
		<% end %>
		<% @software_index.each do |software| %>
		<h2><%= link_to software.name, software %>&nbsp;&nbsp;<small><%= software.short_description %></small></h2>
		<% end %>
	</div>
</div>

app/views/software/landing.html.erb
<div class="jumbotron text-center">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>Discover Linux Software</h1>
				<p>Easily search for software and discover which distros have it in their repositories.</p>
				<br />
				<%= form_tag software_search_form_path, method: :get, enforce_utf8: false, class: "form-inline" do %>
					<div class="form-group has-feedback">
						<%= text_field_tag "query", "", size: "30", class: "form-control" %>
						<span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h2>Recently Updated</h2>
			<% @recent_softwares.each do |software| %>
				<h3><%= link_to software.name, software %> <small><%= software.short_description %></small></h3>
			<% end %>
		</div>
		<div class="col-md-6">
			<h2>Stats</h2>
			<h3><b><%= @num_softwares %></b> <%= "software title".pluralize(@num_softwares) %></h3>
			<h3><b><%= @num_packages %></b> <%= "package".pluralize(@num_packages) %></h3>
			<h3><b><%= @num_distros %></b> <%= "Linux distro".pluralize(@num_distros) %></h3>
			<h3><b><%= @num_repos %></b> <%= "repository".pluralize(@num_repos) %></h3>
		</div>
	</div>
</div>

app/views/software/new.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1>Add Software</h1>
		</div>
		<%= render partial: 'form', locals: {url: software_index_path, method: :post} %>
	</div>
</div>

app/views/software/search.html.erb
<div class="row">
	<div class="page-header">
		<div class="col-md-6"><h1>Search<br /><small><%= @search_results.length %> results</small></h1></div>
		<div class="col-md-6 text-right">
			<%= form_tag software_search_form_path, method: :get, enforce_utf8: false, class: "form-inline" do %>
				<div class="form-group has-feedback">
					<%= text_field_tag "query", @search_query, size: "50", class: "form-control" %>
					<span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>
				</div>
			<% end %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<% if @search_results.length == 0 %>
		<span>No software found.</span>
		<% end %>
		<% @search_results.each do |software| %>
		<h2><%= link_to software.name, software %>&nbsp;&nbsp;<small><%= software.short_description %></small></h2>
		<% end %>
	</div>
</div>

app/views/software/show.html.erb
<div class="row">
	<div class="page-header">
		<div class="col-xs-6"><h1><%= @software.name %></h1></div>
		<div class="col-xs-6 text-right"><%= link_to "Edit", edit_software_path(@software), class: "btn btn-default" %>&nbsp;&nbsp;<%= link_to "Delete", @software, :method => :delete, class: "btn btn-danger" %></div>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="thumbnail">
			<img src="http://placehold.it/480x320" />
			<div class="caption">
				<table class="table">
					<tr><td><b>Official Site:</b></td><td class="text-right"><a href="<%= @software.url %>"><%= @software.url %></a></td></tr>
					<tr><td><b>License:</b></td><td class="text-right"><%= @software.license %></td></tr>
					<% if @software.tags != "" %>
					<tr>
						<td><b>Tags:</b></td>
						<td class="text-right">
							<% @software.tags.split(", ").each do |tag| %>
							<span class="label label-large label-default"><%= tag %></span><br />
							<% end %>
						</td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<h2>Description</h2>
		<p><%= @software.description %></p>

		<h2>Packages</h2>
		<% if @packages.length == 0 %>
		There are no packages available for this software.
		<% else %>
		<table class="table table-hover">
			<% @packages.each do |p| %>
			<tr><th colspan="3"><h3><%= p[:distro] %></h3></th></tr>
			<% p[:packages].each do |pkg| %>
			<tr><td><code><%= pkg[:name] %></code></td><td><%= pkg[:version] %></td><td><%= pkg[:description] %></td></tr>
			<% end %>
			<% end %>
		</table>
		<% end %>
	</div>
</div>